// ドット先生 — 五十音数据
// 包含全部 46 个基础假名：平假名、片假名、罗马音、所属行、示例词、关联词、例句

const KANA_DATA = [
  // ── あ行 (a-row) ──────────────────────────
  { hiragana: 'あ', katakana: 'ア', romaji: 'a',  row: 'a', col: 0,
    example: { word: 'あめ', reading: 'ame', meaning: '雨（あめ）' },
    related: ['あさ（朝 — 早晨）', 'あお（青 — 蓝色）', 'あたま（頭 — 头）', 'あかい（赤い — 红色的）'],
    sentence: 'あさ、あめがふりました。（早晨下雨了。）' },
  { hiragana: 'い', katakana: 'イ', romaji: 'i',  row: 'a', col: 1,
    example: { word: 'いぬ', reading: 'inu', meaning: '犬（いぬ）' },
    related: ['いし（石 — 石头）', 'いち（一 — 一）', 'いま（今 — 现在）', 'いえ（家 — 房子）'],
    sentence: 'いぬがいえのまえにいます。（狗在房子前面。）' },
  { hiragana: 'う', katakana: 'ウ', romaji: 'u',  row: 'a', col: 2,
    example: { word: 'うみ', reading: 'umi', meaning: '海（うみ）' },
    related: ['うた（歌 — 歌曲）', 'うし（牛 — 牛）', 'うえ（上 — 上面）', 'うどん（烏冬 — 乌冬面）'],
    sentence: 'うみでうたをうたいました。（在海边唱了歌。）' },
  { hiragana: 'え', katakana: 'エ', romaji: 'e',  row: 'a', col: 3,
    example: { word: 'えき', reading: 'eki', meaning: '駅（えき）' },
    related: ['えん（円 — 日元）', 'えほん（絵本 — 绘本）', 'えいが（映画 — 电影）', 'えんぴつ（鉛筆 — 铅笔）'],
    sentence: 'えきでえいがのポスターをみた。（在车站看到了电影海报。）' },
  { hiragana: 'お', katakana: 'オ', romaji: 'o',  row: 'a', col: 4,
    example: { word: 'おかし', reading: 'okashi', meaning: 'お菓子（おかし）' },
    related: ['おと（音 — 声音）', 'おんな（女 — 女性）', 'おおきい（大きい — 大的）', 'おんがく（音楽 — 音乐）'],
    sentence: 'おかしをおさらにのせました。（把点心放在了盘子上。）' },

  // ── か行 (ka-row) ──────────────────────────
  { hiragana: 'か', katakana: 'カ', romaji: 'ka',  row: 'ka', col: 0,
    example: { word: 'かさ', reading: 'kasa', meaning: '傘（かさ）' },
    related: ['かわ（川 — 河流）', 'かぜ（風 — 风）', 'かお（顔 — 脸）', 'かみ（紙 — 纸）'],
    sentence: 'かぜがつよいので、かさがこわれた。（风很大，伞坏了。）' },
  { hiragana: 'き', katakana: 'キ', romaji: 'ki',  row: 'ka', col: 1,
    example: { word: 'きもの', reading: 'kimono', meaning: '着物（きもの）' },
    related: ['き（木 — 树）', 'きっぷ（切符 — 票）', 'きいろ（黄色 — 黄色）', 'きのう（昨日 — 昨天）'],
    sentence: 'きのう、きれいなきものをみました。（昨天看到了漂亮的和服。）' },
  { hiragana: 'く', katakana: 'ク', romaji: 'ku',  row: 'ka', col: 2,
    example: { word: 'くも', reading: 'kumo', meaning: '雲（くも）' },
    related: ['くつ（靴 — 鞋子）', 'くるま（車 — 汽车）', 'くすり（薬 — 药）', 'くに（国 — 国家）'],
    sentence: 'くろいくもがそらをおおった。（乌云遮住了天空。）' },
  { hiragana: 'け', katakana: 'ケ', romaji: 'ke',  row: 'ka', col: 3,
    example: { word: 'けしき', reading: 'keshiki', meaning: '景色（けしき）' },
    related: ['けさ（今朝 — 今天早上）', 'けいたい（携帯 — 手机）', 'けむり（煙 — 烟）', 'けんこう（健康 — 健康）'],
    sentence: 'やまのけしきがとてもうつくしい。（山上的景色非常美。）' },
  { hiragana: 'こ', katakana: 'コ', romaji: 'ko',  row: 'ka', col: 4,
    example: { word: 'こころ', reading: 'kokoro', meaning: '心（こころ）' },
    related: ['こども（子供 — 孩子）', 'ことば（言葉 — 语言）', 'こめ（米 — 米）', 'こんにちは（你好）'],
    sentence: 'こどもたちがこうえんであそんでいる。（孩子们在公园里玩。）' },

  // ── さ行 (sa-row) ──────────────────────────
  { hiragana: 'さ', katakana: 'サ', romaji: 'sa',  row: 'sa', col: 0,
    example: { word: 'さくら', reading: 'sakura', meaning: '桜（さくら）' },
    related: ['さかな（魚 — 鱼）', 'さとう（砂糖 — 糖）', 'さむい（寒い — 冷的）', 'さんぽ（散歩 — 散步）'],
    sentence: 'はるにさくらがきれいにさいた。（春天樱花美丽地绽放了。）' },
  { hiragana: 'し', katakana: 'シ', romaji: 'shi', row: 'sa', col: 1,
    example: { word: 'しお', reading: 'shio', meaning: '塩（しお）' },
    related: ['しろ（白 — 白色）', 'しんぶん（新聞 — 报纸）', 'しゃしん（写真 — 照片）', 'しずか（静か — 安静）'],
    sentence: 'しおをすこしいれてください。（请放一点盐。）' },
  { hiragana: 'す', katakana: 'ス', romaji: 'su',  row: 'sa', col: 2,
    example: { word: 'すし', reading: 'sushi', meaning: '寿司（すし）' },
    related: ['すき（好き — 喜欢）', 'すごい（厉害的）', 'すいか（西瓜 — 西瓜）', 'すずしい（涼しい — 凉爽的）'],
    sentence: 'わたしはすしがだいすきです。（我非常喜欢寿司。）' },
  { hiragana: 'せ', katakana: 'セ', romaji: 'se',  row: 'sa', col: 3,
    example: { word: 'せかい', reading: 'sekai', meaning: '世界（せかい）' },
    related: ['せんせい（先生 — 老师）', 'せまい（狭い — 狭窄的）', 'せいと（生徒 — 学生）', 'せつめい（説明 — 说明）'],
    sentence: 'せんせいがせかいちずをみせてくれた。（老师给我们看了世界地图。）' },
  { hiragana: 'そ', katakana: 'ソ', romaji: 'so',  row: 'sa', col: 4,
    example: { word: 'そら', reading: 'sora', meaning: '空（そら）' },
    related: ['そば（旁边 / 荞麦面）', 'そと（外 — 外面）', 'そうじ（掃除 — 打扫）', 'そつぎょう（卒業 — 毕业）'],
    sentence: 'そらにほしがきらきらひかっている。（天空中星星闪闪发光。）' },

  // ── た行 (ta-row) ──────────────────────────
  { hiragana: 'た', katakana: 'タ', romaji: 'ta',  row: 'ta', col: 0,
    example: { word: 'たこ', reading: 'tako', meaning: '蛸（たこ）' },
    related: ['たべる（食べる — 吃）', 'たかい（高い — 高的/贵的）', 'たいよう（太陽 — 太阳）', 'たのしい（楽しい — 快乐的）'],
    sentence: 'たこやきをたべにいきました。（去吃了章鱼烧。）' },
  { hiragana: 'ち', katakana: 'チ', romaji: 'chi', row: 'ta', col: 1,
    example: { word: 'ちず', reading: 'chizu', meaning: '地図（ちず）' },
    related: ['ちかい（近い — 近的）', 'ちいさい（小さい — 小的）', 'ちから（力 — 力量）', 'ちゃ（茶 — 茶）'],
    sentence: 'ちずをみながらまちをあるいた。（一边看地图一边在街上走。）' },
  { hiragana: 'つ', katakana: 'ツ', romaji: 'tsu', row: 'ta', col: 2,
    example: { word: 'つき', reading: 'tsuki', meaning: '月（つき）' },
    related: ['つくえ（机 — 桌子）', 'つめたい（冷たい — 冰凉的）', 'つよい（強い — 强的）', 'つぎ（次 — 下一个）'],
    sentence: 'まんげつのつきがとてもあかるい。（满月非常明亮。）' },
  { hiragana: 'て', katakana: 'テ', romaji: 'te',  row: 'ta', col: 3,
    example: { word: 'てがみ', reading: 'tegami', meaning: '手紙（てがみ）' },
    related: ['てんき（天気 — 天气）', 'てつだう（手伝う — 帮忙）', 'てら（寺 — 寺庙）', 'てん（点 — 分数/点）'],
    sentence: 'ともだちにてがみをかきました。（给朋友写了信。）' },
  { hiragana: 'と', katakana: 'ト', romaji: 'to',  row: 'ta', col: 4,
    example: { word: 'とり', reading: 'tori', meaning: '鳥（とり）' },
    related: ['とけい（時計 — 钟表）', 'ともだち（友達 — 朋友）', 'としょかん（図書館 — 图书馆）', 'とおい（遠い — 远的）'],
    sentence: 'とりがそらをとんでいます。（鸟儿在天空飞翔。）' },

  // ── な行 (na-row) ──────────────────────────
  { hiragana: 'な', katakana: 'ナ', romaji: 'na',  row: 'na', col: 0,
    example: { word: 'なつ', reading: 'natsu', meaning: '夏（なつ）' },
    related: ['なまえ（名前 — 名字）', 'なに（何 — 什么）', 'ながい（長い — 长的）', 'ならぶ（並ぶ — 排列）'],
    sentence: 'なつやすみにうみへいきました。（暑假去了海边。）' },
  { hiragana: 'に', katakana: 'ニ', romaji: 'ni',  row: 'na', col: 1,
    example: { word: 'にほん', reading: 'nihon', meaning: '日本（にほん）' },
    related: ['にわ（庭 — 庭院）', 'にく（肉 — 肉）', 'にちようび（日曜日 — 星期天）', 'にんぎょう（人形 — 人偶）'],
    sentence: 'にほんごをべんきょうしています。（正在学习日语。）' },
  { hiragana: 'ぬ', katakana: 'ヌ', romaji: 'nu',  row: 'na', col: 2,
    example: { word: 'ぬの', reading: 'nuno', meaning: '布（ぬの）' },
    related: ['ぬま（沼 — 沼泽）', 'ぬる（塗る — 涂）', 'ぬぐ（脱ぐ — 脱）', 'ぬいぐるみ（布偶）'],
    sentence: 'ぬのでふくをつくりました。（用布做了衣服。）' },
  { hiragana: 'ね', katakana: 'ネ', romaji: 'ne',  row: 'na', col: 3,
    example: { word: 'ねこ', reading: 'neko', meaning: '猫（ねこ）' },
    related: ['ねむい（眠い — 困的）', 'ねだん（値段 — 价格）', 'ねつ（熱 — 热度）', 'ねがい（願い — 愿望）'],
    sentence: 'ねこがにわでひるねしている。（猫在院子里午睡。）' },
  { hiragana: 'の', katakana: 'ノ', romaji: 'no',  row: 'na', col: 4,
    example: { word: 'のり', reading: 'nori', meaning: '海苔（のり）' },
    related: ['のど（喉咙）', 'のぼる（登る — 攀登）', 'のりもの（乗り物 — 交通工具）', 'のんびり（悠闲地）'],
    sentence: 'のりまきをじょうずにつくった。（很好地做了寿司卷。）' },

  // ── は行 (ha-row) ──────────────────────────
  { hiragana: 'は', katakana: 'ハ', romaji: 'ha',  row: 'ha', col: 0,
    example: { word: 'はな', reading: 'hana', meaning: '花（はな）' },
    related: ['はし（橋 — 桥 / 箸 — 筷子）', 'はやい（速い — 快的）', 'はる（春 — 春天）', 'はじめ（初め — 开始）'],
    sentence: 'にわにはながたくさんさいている。（院子里开了很多花。）' },
  { hiragana: 'ひ', katakana: 'ヒ', romaji: 'hi',  row: 'ha', col: 1,
    example: { word: 'ひかり', reading: 'hikari', meaning: '光（ひかり）' },
    related: ['ひと（人 — 人）', 'ひる（昼 — 白天）', 'ひこうき（飛行機 — 飞机）', 'ひろい（広い — 宽广的）'],
    sentence: 'たいようのひかりがまぶしい。（太阳光很刺眼。）' },
  { hiragana: 'ふ', katakana: 'フ', romaji: 'fu',  row: 'ha', col: 2,
    example: { word: 'ふじさん', reading: 'fujisan', meaning: '富士山（ふじさん）' },
    related: ['ふゆ（冬 — 冬天）', 'ふく（服 — 衣服）', 'ふるい（古い — 旧的）', 'ふたり（二人 — 两个人）'],
    sentence: 'ふゆにふじさんにのぼりました。（冬天爬了富士山。）' },
  { hiragana: 'へ', katakana: 'ヘ', romaji: 'he',  row: 'ha', col: 3,
    example: { word: 'へや', reading: 'heya', meaning: '部屋（へや）' },
    related: ['へび（蛇 — 蛇）', 'へん（変 — 奇怪）', 'へた（下手 — 不擅长）', 'へいわ（平和 — 和平）'],
    sentence: 'へやのなかがあかるくなった。（房间里变亮了。）' },
  { hiragana: 'ほ', katakana: 'ホ', romaji: 'ho',  row: 'ha', col: 4,
    example: { word: 'ほし', reading: 'hoshi', meaning: '星（ほし）' },
    related: ['ほん（本 — 书）', 'ほどう（歩道 — 人行道）', 'ほっかいどう（北海道）', 'ほんとう（本当 — 真的）'],
    sentence: 'よぞらのほしをながめるのがすきです。（喜欢仰望夜空中的星星。）' },

  // ── ま行 (ma-row) ──────────────────────────
  { hiragana: 'ま', katakana: 'マ', romaji: 'ma',  row: 'ma', col: 0,
    example: { word: 'まち', reading: 'machi', meaning: '町（まち）' },
    related: ['まいにち（毎日 — 每天）', 'まど（窓 — 窗户）', 'まっすぐ（笔直地）', 'まんが（漫画 — 漫画）'],
    sentence: 'まちはおおにぎわいでした。（街上非常热闹。）' },
  { hiragana: 'み', katakana: 'ミ', romaji: 'mi',  row: 'ma', col: 1,
    example: { word: 'みず', reading: 'mizu', meaning: '水（みず）' },
    related: ['みせ（店 — 商店）', 'みち（道 — 道路）', 'みどり（緑 — 绿色）', 'みらい（未来 — 未来）'],
    sentence: 'みずをのんでいっぷくした。（喝了水休息了一下。）' },
  { hiragana: 'む', katakana: 'ム', romaji: 'mu',  row: 'ma', col: 2,
    example: { word: 'むし', reading: 'mushi', meaning: '虫（むし）' },
    related: ['むずかしい（難しい — 难的）', 'むこう（向こう — 对面）', 'むら（村 — 村庄）', 'むかし（昔 — 从前）'],
    sentence: 'なつになるとむしのこえがきこえる。（到了夏天就能听到虫鸣。）' },
  { hiragana: 'め', katakana: 'メ', romaji: 'me',  row: 'ma', col: 3,
    example: { word: 'めがね', reading: 'megane', meaning: '眼鏡（めがね）' },
    related: ['め（目 — 眼睛）', 'めし（飯 — 饭）', 'めんどう（麻烦）', 'めずらしい（珍しい — 稀奇的）'],
    sentence: 'めがねをかけてほんをよんだ。（戴着眼镜看了书。）' },
  { hiragana: 'も', katakana: 'モ', romaji: 'mo',  row: 'ma', col: 4,
    example: { word: 'もり', reading: 'mori', meaning: '森（もり）' },
    related: ['もも（桃 — 桃子）', 'もんだい（問題 — 问题）', 'もち（年糕）', 'もちろん（当然）'],
    sentence: 'もりのなかをさんぽするのがだいすき。（非常喜欢在森林里散步。）' },

  // ── や行 (ya-row) ──────────────────────────
  { hiragana: 'や', katakana: 'ヤ', romaji: 'ya',  row: 'ya', col: 0,
    example: { word: 'やま', reading: 'yama', meaning: '山（やま）' },
    related: ['やすみ（休み — 休息）', 'やさい（野菜 — 蔬菜）', 'やさしい（優しい — 温柔的）', 'やくそく（約束 — 约定）'],
    sentence: 'やまのうえからまちがみえた。（从山上能看到城镇。）' },
  { hiragana: 'ゆ', katakana: 'ユ', romaji: 'yu',  row: 'ya', col: 1,
    example: { word: 'ゆき', reading: 'yuki', meaning: '雪（ゆき）' },
    related: ['ゆめ（夢 — 梦）', 'ゆうびん（郵便 — 邮政）', 'ゆか（床 — 地板）', 'ゆうめい（有名 — 有名）'],
    sentence: 'ゆきがふって、まちがしろくなった。（下了雪，城镇变白了。）' },
  { hiragana: 'よ', katakana: 'ヨ', romaji: 'yo',  row: 'ya', col: 2,
    example: { word: 'よる', reading: 'yoru', meaning: '夜（よる）' },
    related: ['よむ（読む — 读）', 'よわい（弱い — 弱的）', 'ようふく（洋服 — 西服）', 'よてい（予定 — 计划）'],
    sentence: 'よる、ほんをよむのがしゅうかんです。（晚上读书是我的习惯。）' },

  // ── ら行 (ra-row) ──────────────────────────
  { hiragana: 'ら', katakana: 'ラ', romaji: 'ra',  row: 'ra', col: 0,
    example: { word: 'らいねん', reading: 'rainen', meaning: '来年（らいねん）' },
    related: ['らいげつ（来月 — 下个月）', 'らく（楽 — 轻松）', 'ラーメン（拉面）', 'らいしゅう（来週 — 下周）'],
    sentence: 'らいねん、にほんへいくよていです。（计划明年去日本。）' },
  { hiragana: 'り', katakana: 'リ', romaji: 'ri',  row: 'ra', col: 1,
    example: { word: 'りんご', reading: 'ringo', meaning: '林檎（りんご）' },
    related: ['りょうり（料理 — 料理）', 'りょこう（旅行 — 旅行）', 'りゆう（理由 — 理由）', 'りっぱ（立派 — 出色）'],
    sentence: 'あかいりんごをひとつください。（请给我一个红苹果。）' },
  { hiragana: 'る', katakana: 'ル', romaji: 'ru',  row: 'ra', col: 2,
    example: { word: 'るす', reading: 'rusu', meaning: '留守（るす）' },
    related: ['るーる（规则 — 规则）', 'るび（振り仮名 — 注音假名）', 'るい（類 — 种类）', 'るてん（流転 — 流转）'],
    sentence: 'るすのあいだに、にもつがとどいた。（不在家期间，包裹送到了。）' },
  { hiragana: 'れ', katakana: 'レ', romaji: 're',  row: 'ra', col: 3,
    example: { word: 'れきし', reading: 'rekishi', meaning: '歴史（れきし）' },
    related: ['れんしゅう（練習 — 练习）', 'れいぞうこ（冷蔵庫 — 冰箱）', 'れつ（列 — 队列）', 'れんらく（連絡 — 联系）'],
    sentence: 'れきしのじゅぎょうがとてもおもしろかった。（历史课非常有趣。）' },
  { hiragana: 'ろ', katakana: 'ロ', romaji: 'ro',  row: 'ra', col: 4,
    example: { word: 'ろく', reading: 'roku', meaning: '六（ろく）' },
    related: ['ろうか（廊下 — 走廊）', 'ろんぶん（論文 — 论文）', 'ろうじん（老人 — 老人）', 'ろめん（路面 — 路面）'],
    sentence: 'えきまでろくふんあるきます。（走到车站要六分钟。）' },

  // ── わ行 (wa-row) + ん ──────────────────────
  { hiragana: 'わ', katakana: 'ワ', romaji: 'wa',  row: 'wa', col: 0,
    example: { word: 'わたし', reading: 'watashi', meaning: '私（わたし）' },
    related: ['わかい（若い — 年轻的）', 'わらう（笑う — 笑）', 'わすれる（忘れる — 忘记）', 'わかれる（別れる — 分别）'],
    sentence: 'わたしはまいにちにほんごをべんきょうしています。（我每天学习日语。）' },
  { hiragana: 'を', katakana: 'ヲ', romaji: 'wo',  row: 'wa', col: 1,
    example: { word: 'を', reading: 'wo', meaning: '助詞（じょし）' },
    related: ['ほんをよむ（读书）', 'ごはんをたべる（吃饭）', 'テレビをみる（看电视）', 'うたをうたう（唱歌）'],
    sentence: 'わたしはまいあさ、コーヒーをのみます。（我每天早上喝咖啡。）' },
  { hiragana: 'ん', katakana: 'ン', romaji: 'n',   row: 'n',  col: 0,
    example: { word: 'にほん', reading: 'nihon', meaning: '日本（にほん）' },
    related: ['れんしゅう（練習 — 练习）', 'しんぶん（新聞 — 报纸）', 'えん（円 — 日元）', 'ほん（本 — 书）'],
    sentence: 'にほんのぶんかにとてもきょうみがある。（对日本文化非常感兴趣。）' },
];

// ── 行定义 ────────────────────────────────────
const KANA_ROWS = [
  { id: 'a',  label: 'あ行', labelRomaji: 'a-row',  count: 5 },
  { id: 'ka', label: 'か行', labelRomaji: 'ka-row', count: 5 },
  { id: 'sa', label: 'さ行', labelRomaji: 'sa-row', count: 5 },
  { id: 'ta', label: 'た行', labelRomaji: 'ta-row', count: 5 },
  { id: 'na', label: 'な行', labelRomaji: 'na-row', count: 5 },
  { id: 'ha', label: 'は行', labelRomaji: 'ha-row', count: 5 },
  { id: 'ma', label: 'ま行', labelRomaji: 'ma-row', count: 5 },
  { id: 'ya', label: 'や行', labelRomaji: 'ya-row', count: 3 },
  { id: 'ra', label: 'ら行', labelRomaji: 'ra-row', count: 5 },
  { id: 'wa', label: 'わ行', labelRomaji: 'wa-row', count: 3 },
];

// ── 辅助函数 ──────────────────────────────────
function getKanaByRow(rowId) {
  return KANA_DATA.filter(k => k.row === rowId);
}

function getKanaByIndex(index) {
  return KANA_DATA[index] || null;
}

function getAllRows() {
  return KANA_ROWS;
}
